---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Services:
    - Dashboard:
        icon: https://cdn.jsdelivr.net/gh/gethomepage/homepage@main/public/android-chrome-192x192.png
        href: http://10.0.0.30:3000/
    - Glances:
        icon: glances
        href: http://10.0.0.30:61208/
    - Jellyfin:
        icon: jellyfin
        href: http://10.0.0.30:8096/
    - Pi-hole:
        icon: pi-hole
        href: http://10.0.0.30/admin/
    - qbittorrent:
        icon: qbittorrent
        href: http://10.0.0.30:8080/
    - Navidrome:
        icon: navidrome
        href: http://10.0.0.30:4533/

- Performance:
    - CPU Usage:
        widget:
          type: glances
          url: http://10.0.0.30:61208/
          version: 4
          metric: cpu
    - Memory Usage:
        widget:
          type: glances
          url: http://10.0.0.30:61208/
          version: 4
          metric: memory
    - Network Usage:
        widget:
          type: glances
          url: http://10.0.0.30:61208/
          version: 4
          metric: network:wlan0
    - Top Processes:
        widget:
          type: glances
          url: http://10.0.0.30:61208/
          version: 4
          metric: process
    - CPU Temp:
        widget:
          type: glances
          url: http://10.0.0.30:61208/
          version: 4
          metric: sensor:cpu_thermal 0
    - Disk I/O:
        widget:
          type: glances
          url: http://10.0.0.30:61208/
          version: 4
          metric: disk:mmcblk0
